export default [
  {
    author: "Dan Peck",
    title: "Hurricane Hanna makes landfall around 5 p.m. on Saturday.",
    description:
      "Hurricane Hanna battered southern Texas with sustained winds of 75 mph and continued to deliver heavy rain and flash flooding as it moved inland late Saturday.",
    sold_out: "1",
    source: "ABC News",
    image: "imgs/insta-1.jpg",
    category: "general",
    language: "en",
    id: "1",
    published_at: "2020-07-26T01:04:23+00:00",
    job: "back-end engineer",
  },
  {
    author: "TMZ Staff",
    title: "Nicki Minaj's Husband Gets Permission To Be There For Baby's Birth",
    description:
      "Kenneth can be in the room when Nicki gives birth ... a judge just granted his request to tweak his pre-trial release conditions so he can travel with Nicki. With the court's order in place, KP can travel with Nicki periodically on biz…",
    sold_out: "0",
    source: "TMZ.com",
    image: "imgs/insta-2.jpg",
    category: "general",
    language: "en",
    id: "2",
    published_at: "2020-08-01T05:34:47+00:00",
    job: "full stack engineer",
  },
  {
    author: "david clarj",
    title: "New Lions safety Jayron Kearse suspended three games",
    description:
      "Kearse, 26, signed with the Lions in March after four seasons in Minnesota, where he played in 62 games with five starts, making 79 tackles and defending eight passes.",
    sold_out: "0",
    source: "ESPN",
    image: "imgs/insta-3.jpg",
    category: "sports",
    language: "en",
    id: "3",
    published_at: "2020-07-31T23:23:14+00:00",
    job: "web designer",
  },
  {
    author: "mikel felix",
    title: "New Lions safety Jayron Kearse suspended three games",
    description:
      "Kearse, 26, signed with the Lions in March after four seasons in Minnesota, where he played in 62 games with five starts, making 79 tackles and defending eight passes.",
    sold_out: "0",
    source: "ESPN",
    image: "imgs/insta-5.jpg",
    category: "sports",
    language: "en",
    id: "4",
    published_at: "2020-07-31T23:23:14+00:00",
    job: "front-end engineer",
  },
  {
    author: "sanchez gad",
    title: "New Lions safety Jayron Kearse suspended three games",
    description:
      "Kearse, 26, signed with the Lions in March after four seasons in Minnesota, where he played in 62 games with five starts, making 79 tackles and defending eight passes.",
    sold_out: "1",
    source: "ESPN",
    image: "imgs/insta-6.jpg",
    category: "sports",
    language: "en",
    id: "5",
    published_at: "2020-07-31T23:23:14+00:00",
    job: "app dev engineer",
  },
];
